apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - https://github.com/ansible/awx-operator/config/rbac?ref=2.7.1
  - https://github.com/ansible/awx-operator/config/manager?ref=2.7.1
  - awx-demo.yml
  - prout.yml
images:
  - name: quay.io/ansible/awx-operator
    newTag: 2.7.1
namespace: awx
patches:
  - target:
      group: apps
      version: v1
      kind: Deployment
    path: patch-controller-manager-specs.yaml
generatorOptions:
  disableNameSuffixHash: true
