apiVersion: apps/v1
kind: Deployment
metadata:
  name: controller-manager
spec:
  template:
    spec:
      containers:
      - name: awx-manager
        resources:
          limits:
            cpu: 1000m
            memory: 2048Mi
